# This should contain tracker parameters

line_tracker_distance:
  default_v_des: 0.5
  default_a_des: 0.5
  epsilon: 0.1

line_tracker_min_jerk:
  default_v_des: 0.3
  default_a_des: 0.6
  default_yaw_v_des: 0.8
  default_yaw_a_des: 0.6

trajectory_tracker:
  max_vel_des: 2.0
  max_acc_des: 2.0

velocity_tracker:
  timeout: 0.5

lissajous_tracker:
  frame_id: simulator

lissajous_adder:
  frame_id: simulator


stopping_policy:
  default_a_des: 1.0
  default_j_des: 2.0
